'use strict';function z(h,a,b,d){h.A.oc(h.Za,a,b,d,void 0)}function F(h,a,b,d){h.A.ca?z(h,a,b,d):h.A.ef()._OnMessageFromDOM({type:"event",component:h.Za,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function H(h,a,b){h.A.C(h.Za,a,b)}function J(h,a){for(const [b,d]of a)H(h,b,d)}function L(h){h.Ob||(h.A.Qe(h.ae),h.Ob=!0)}window.hc=class{constructor(h,a){this.A=h;this.Za=a;this.Ob=!1;this.ae=()=>this.Ca()}ed(){}Ca(){}};function M(h){-1!==h.Pa&&(self.clearTimeout(h.Pa),h.Pa=-1)}
window.He=class{constructor(h,a){this.Lc=h;this.ug=a;this.Pa=-1;this.Pb=-Infinity;this.be=()=>{this.Pa=-1;this.Pb=Date.now();this.eb=!0;this.Lc();this.eb=!1};this.Kd=this.eb=!1}c(){M(this);this.be=this.Lc=null}};"use strict";function N(h,a){H(h,"get-element",b=>{const d=h.ba.get(b.elementId);return a(d,b)})}
window.Pg=class extends self.hc{constructor(h,a){super(h,a);this.ba=new Map;this.Kc=!0;J(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ba.get(b);this.Kc&&d.parentElement.removeChild(d);this.ba.delete(b)}}],["set-visible",b=>{this.Kc&&(this.ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Kc){var d=this.ba.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ba.get(b.elementId);throw Error("required override");}],["focus",b=>{{const d=this.ba.get(b.elementId);b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ba.get(b.elementId).removeAttribute(b.name)}]]);N(this,b=>b)}};"use strict";
{const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(f){const c=document.createElement("script");c.async=!1;c.type="module";return f.Fg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=f.Jg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=f;document.head.appendChild(c)})}let d=!1,g=!1;function m(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(f){}d=!0}return g}let p=
new Audio;const w={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(f){f=await B(f);return(new TextDecoder("utf-8")).decode(f)}function B(f){return new Promise((c,
k)=>{const l=new FileReader;l.onload=n=>c(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(f)})}const u=[];let v=0;window.RealFile=window.File;const C=[],G=new Map,y=new Map;let I=0;const D=[];self.runOnStartup=function(f){if("function"!==typeof f)throw Error("runOnStartup called without a function");D.push(f)};const K=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.qc=class f{constructor(c){this.ca=c.Lg;this.oa=null;this.F="";this.ac=c.Ig;this.tb={};this.Ia=this.sb=null;
this.Mb=[];this.hb=this.K=this.Na=null;this.Ma=-1;this.zg=()=>this.Ef();this.La=[];this.v=c.ce;this.fb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Rb=this.ha=null;"html5"!==
this.v&&"playable-ad"!==this.v||!this.fb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.v||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.nf(k));this.C("runtime",
"create-job-worker",()=>this.pf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.wd(c)):this.wd(c)}c(){this.vc();this.oa&&(this.oa=this.oa.onmessage=null);this.sb&&(this.sb.terminate(),this.sb=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Ce(){return h&&"cordova"===this.v}nc(){const c=navigator.userAgent;return h&&K.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async wd(c){"macos-wkwebview"===
this.v&&this.Xf();if("playable-ad"===this.v){this.ha=self.c3_base64files;this.Rb={};await this.Ve();for(let l=0,n=c.Qa.length;l<n;++l){var k=c.Qa[l].toLowerCase();this.Rb.hasOwnProperty(k)?c.Qa[l]={Fg:!0,Jg:this.Rb[k]}:this.ha.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ha[k]))}}c.Ag?this.F=c.Ag:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Ng&&(this.tb=c.Ng);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=
l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Af(l));this.hb=new self.De(this);await O(this.hb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.gf(c,k.port2):await this.ff(c,k.port2)}yc(c){c=this.tb.hasOwnProperty(c)?this.tb[c]:c.endsWith("/workermain.js")&&this.tb.hasOwnProperty("workermain.js")?this.tb["workermain.js"]:
"playable-ad"===this.v&&this.ha.hasOwnProperty(c.toLowerCase())?this.ha[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async fc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.v&&this.fb)return c=await this.ub(l.Eg?c:this.ac+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),
l)}return new Worker(c,l)}va(){return Math.max(window.innerWidth,1)}ua(){return Math.max(window.innerHeight,1)}vd(c){var k=this.hb;return{baseUrl:this.F,windowInnerWidth:this.va(),windowInnerHeight:this.ua(),devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Ta(),projectData:c.Tg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Rg||"",exportType:c.ce,isDebug:-1<
self.location.search.indexOf("debug"),ife:!!self.Sg,jobScheduler:{inputPort:k.Rc,outputPort:k.Xc,maxNumWorkers:k.wg},supportedAudioFormats:w,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ac+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ac+"opus.wasm.wasm",isFileProtocol:this.fb,isiOSCordova:this.Ce(),isiOSWebView:this.nc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async gf(c,k){var l=this.yc(c.Mg);this.sb=await this.fc(l,this.F,{type:"module",name:"Runtime",
Eg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;let n=c.cd||[],t=c.Qa;n=await Promise.all(n.map(q=>this.Da(q)));t=await Promise.all(t.map(q=>this.Da(q)));if("cordova"===this.v)for(let q=0,r=c.dc.length;q<r;++q){const x=c.dc[q],E=x[0];if(E===c.ad||"scriptsInEvents.js"===E||E.endsWith("/scriptsInEvents.js"))x[1]=await this.Da(E)}this.sb.postMessage(Object.assign(this.vd(c),{type:"init-runtime",
isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:n,engineScripts:t,projectScripts:c.dc,mainProjectScript:c.ad,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...P(this.hb)]);this.Mb=C.map(q=>new q(this));this.ud();self.c3_callFunction=(q,r)=>this.Na.hf(q,r);"preview"===this.v&&(self.goToLastErrorScript=()=>this.oc("runtime","go-to-last-error-script"))}async ff(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=
this.K;this.Mb=C.map(q=>new q(this));this.ud();var l=c.Qa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(c.cd)&&l.unshift(...c.cd);l=await Promise.all(l.map(q=>this.Da(q)));await Promise.all(l.map(q=>b(q)));l=self.C3_ProjectScriptsStatus;const n=c.ad,t=c.dc;for(let [q,r]of t)if(r||(r=q),q===n)try{r=await this.Da(r),await b(r),"preview"!==this.v||l[q]||this.Ed(q,"main script did not run to completion")}catch(x){this.Ed(q,x)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))r=
await this.Da(r),await b(r);"preview"===this.v&&"object"!==typeof self.Og.Qg?(this.Gb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.vd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:D}),this.yd(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,c))}Ed(c,
k){this.Gb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}yd(){this.Gb()}Gb(){const c=window.Bg;c&&(c.parentElement.removeChild(c),window.Bg=null)}async pf(){const c=await Q(this.hb);return{outputPort:c,transferables:[c]}}ef(){if(this.ca)throw Error("not available in worker mode");return this.Ia}oc(c,k,l,n,t){this.oa.postMessage({type:"event",
component:c,handler:k,dispatchOpts:n||null,data:l,responseId:null},t)}nd(c,k,l,n,t){const q=I++,r=new Promise((x,E)=>{y.set(q,{resolve:x,reject:E})});this.oa.postMessage({type:"event",component:c,handler:k,dispatchOpts:n||null,data:l,responseId:q},t);return r}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.uf(c);if("result"===k)this.Hf(c);else if("runtime-ready"===k)this.If();else if("alert-error"===k)this.Gb(),alert(c.message);else if("creating-runtime"===k)this.yd();else throw Error(`unknown message '${k}'`);
}uf(c){const k=c.component,l=c.handler,n=c.data,t=c.responseId;if(c=G.get(k))if(c=c.get(l)){var q=null;try{q=c(n)}catch(r){console.error(`Exception in '${k}' handler '${l}':`,r);null!==t&&this.Fb(t,!1,""+r);return}if(null===t)return q;q&&q.then?q.then(r=>this.Fb(t,!0,r)).catch(r=>{console.error(`Rejection from '${k}' handler '${l}':`,r);this.Fb(t,!1,""+r)}):this.Fb(t,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Fb(c,
k,l){let n;l&&l.transferables&&(n=l.transferables);this.oa.postMessage({type:"result",responseId:c,isOk:k,result:l},n)}Hf(c){const k=c.responseId,l=c.isOk;c=c.result;const n=y.get(k);l?n.resolve(c):n.reject(c);y.delete(k)}C(c,k,l){let n=G.get(c);n||(n=new Map,G.set(c,n));if(n.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);n.set(k,l)}static dd(c){if(C.includes(c))throw Error("DOM handler already added");C.push(c)}ud(){for(const c of this.Mb)if("runtime"===c.Za){this.Na=c;return}throw Error("cannot find runtime DOM handler");
}Af(c){this.oc("debugger","message",c)}If(){for(const c of this.Mb)c.ed()}static Ta(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||e)}static Fd(c){e=!!c}Qe(c){this.La.push(c);this.Ic()}Uf(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.vc()}Ic(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.zg))}vc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Ef(){this.Ma=
-1;for(const c of this.La)c();this.Ic()}ta(c){this.Na.ta(c)}Ba(c){this.Na.Ba(c)}Hc(){this.Na.Hc()}Ab(c){this.Na.Ab(c)}Be(){return!!w["audio/webm; codecs=opus"]}async sg(c){c=await this.nd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Ae(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}md(c){return!this.Ae(c)}async Da(c){return"cordova"===this.v&&(c.startsWith("file:")||this.fb&&this.md(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),
c=await this.ub(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async nf(c){const k=c.filename;switch(c.as){case "text":return await this.te(k);case "buffer":return await this.ub(k);default:throw Error("unsupported type");}}hd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,t=>{t.file(l,n)},n)})}async te(c){c=await this.hd(c);return await A(c)}wc(){if(u.length&&!(8<=v)){v++;var c=u.shift();
this.We(c.filename,c.Kg,c.Dg)}}ub(c){return new Promise((k,l)=>{u.push({filename:c,Kg:n=>{v--;this.wc();k(n)},Dg:n=>{v--;this.wc();l(n)}});this.wc()})}async We(c,k,l){try{const n=await this.hd(c),t=await B(n);k(t)}catch(n){l(n)}}Xf(){var c={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async Ve(){const c=
[];for(const [k,l]of Object.entries(this.ha))c.push(this.Ue(k,l));await Promise.all(c)}async Ue(c,k){if("object"===typeof k)this.ha[c]=new Blob([k.str],{type:k.type}),this.Rb[c]=k.str;else{let l=await this.cf(k);l||(l=this.Ye(k));this.ha[c]=l}}async cf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}Ye(c){c=this.Of(c);return this.Te(c.data,c.Gg)}Of(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Gg:c,data:l}}Te(c,k){var l=c.length;let n=l>>2,t=new Uint8Array(l),q=new Uint32Array(t.buffer,0,n),r,x;for(x=r=0;r<n;++r)q[r]=c.charCodeAt(x++)|c.charCodeAt(x++)<<8|c.charCodeAt(x++)<<16|c.charCodeAt(x++)<<24;for(l&=
3;l--;)t[x]=c.charCodeAt(x),++x;return new Blob([t],{type:k})}}}"use strict";
{const h=self.qc;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((f,c)=>{const k=document.createElement("link");k.onload=()=>f(k);k.onerror=l=>c(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function w(e){return new Promise((f,c)=>{const k=new Image;k.onload=()=>f(k);k.onerror=l=>c(l);k.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await w(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((f,c)=>{let k=new FileReader;k.onload=l=>f(l.target.result);k.onerror=l=>c(l);k.readAsText(e)})}async function u(e,f,c){if(!/firefox/i.test(navigator.userAgent))return await A(e);var k=await B(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),t=l.getAttribute("height");if(!n.includes("%")&&!t.includes("%"))return await A(e)}l.setAttribute("width",f+"px");l.setAttribute("height",c+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await A(e)}function v(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function y(e){G.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function I(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const f=e.getBoundingClientRect();document.body.removeChild(e);return[f.width,
f.height]}};self.C3_RasterSvgImageBlob=async function(e,f,c,k,l){e=await u(e,f,c);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(e,0,0,f,c);return n};let D=!1;document.addEventListener("pause",()=>D=!0);document.addEventListener("resume",()=>D=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}h.dd(class extends self.hc{constructor(e){super(e,"runtime");this.Pd=!0;this.Oa=-1;this.Zc="any";this.Gd=this.Hd=!1;this.Ha=
this.pb=this.xa=null;this.Xb=this.Wb=0;e.C("canvas","update-size",k=>this.Lf(k));e.C("runtime","invoke-download",k=>this.yf(k));e.C("runtime","raster-svg-image",k=>this.Ff(k));e.C("runtime","get-svg-image-size",k=>this.wf(k));e.C("runtime","set-target-orientation",k=>this.Jf(k));e.C("runtime","register-sw",()=>this.Gf());e.C("runtime","post-to-debugger",k=>this.Ad(k));e.C("runtime","go-to-script",k=>this.Ad(k));e.C("runtime","before-start-ticking",()=>this.mf());e.C("runtime","debug-highlight",k=>
this.qf(k));e.C("runtime","enable-device-orientation",()=>this.Se());e.C("runtime","enable-device-motion",()=>this.Re());e.C("runtime","add-stylesheet",k=>this.kf(k));e.C("runtime","alert",k=>this.lf(k));e.C("runtime","hide-cordova-splash",()=>this.xf());const f=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;f.has(l.tagName.toLowerCase())||v(l)||k.preventDefault()});const c=e.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",
y);c.addEventListener("selectstart",y);c.addEventListener("gesturehold",y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),c.addEventListener("pointerdown",y)):c.addEventListener("touchstart",y);this.mb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",I,{passive:!1});window.addEventListener("wheel",I,{passive:!1});window.addEventListener("resize",
()=>this.Mf());window.addEventListener("fullscreenchange",()=>this.Va());window.addEventListener("webkitfullscreenchange",()=>this.Va());window.addEventListener("mozfullscreenchange",()=>this.Va());window.addEventListener("fullscreenerror",k=>this.Dc(k));window.addEventListener("webkitfullscreenerror",k=>this.Dc(k));window.addEventListener("mozfullscreenerror",k=>this.Dc(k));e.nc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):v(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.Nf(k);this.Ja=new Set;this.Sb=new WeakSet;this.na=!1}mf(){"cordova"===this.A.v?(document.addEventListener("pause",()=>this.Gc(!0)),document.addEventListener("resume",()=>this.Gc(!1))):document.addEventListener("visibilitychange",()=>this.Gc(document.hidden));return{isSuspended:!(!document.hidden&&!D)}}ed(){window.addEventListener("focus",()=>
this.Xa("window-focus"));window.addEventListener("blur",()=>{this.Xa("window-blur",{parentHasFocus:K()});this.mb=0});window.addEventListener("focusin",f=>{f=f.target;(C.has(f.tagName.toLowerCase())||v(f))&&this.Xa("keyboard-blur")});window.addEventListener("keydown",f=>this.zd("keydown",f));window.addEventListener("keyup",f=>this.zd("keyup",f));window.addEventListener("dblclick",f=>this.Ec("dblclick",f,d));window.addEventListener("wheel",f=>this.Cf(f));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
f=>{this.zc(f);this.Wa("pointerdown",f)}),this.A.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.pb=new self.He(()=>this.af(),5),this.pb.Kd=!0,window.addEventListener("pointerrawupdate",f=>this.Df(f))):window.addEventListener("pointermove",f=>this.Wa("pointermove",f)),window.addEventListener("pointerup",f=>this.Wa("pointerup",f)),window.addEventListener("pointercancel",f=>this.Wa("pointercancel",f))):(window.addEventListener("mousedown",f=>{this.zc(f);this.Fc("pointerdown",
f)}),window.addEventListener("mousemove",f=>this.Fc("pointermove",f)),window.addEventListener("mouseup",f=>this.Fc("pointerup",f)),window.addEventListener("touchstart",f=>{this.zc(f);this.Eb("pointerdown",f)}),window.addEventListener("touchmove",f=>this.Eb("pointermove",f)),window.addEventListener("touchend",f=>this.Eb("pointerup",f)),window.addEventListener("touchcancel",f=>this.Eb("pointercancel",f)));const e=()=>this.Hc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Xa(e,f){z(this,e,f||null,m)}va(){return this.A.va()}ua(){return this.A.ua()}Mf(){const e=this.va(),f=this.ua();this.Xa("window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Ta()});this.A.nc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Bd(e,f,0))}Vf(e,f,c){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Bd(e,
f,c),48)}Bd(e,f,c){const k=this.va(),l=this.ua();this.Oa=-1;k!=e||l!=f?this.Xa("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Ta()}):10>c&&this.Vf(k,l,c+1)}Jf(e){this.Zc=e.targetOrientation}og(){const e=this.Zc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(e):screen.webkitLockOrientation?
f=screen.webkitLockOrientation(e):screen.mozLockOrientation?f=screen.mozLockOrientation(e):screen.msLockOrientation&&(f=screen.msLockOrientation(e));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",f)}}Va(){const e=h.Ta();e&&"any"!==this.Zc&&this.og();z(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.va(),innerHeight:this.ua()})}Dc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);z(this,"fullscreenerror",
{isFullscreen:h.Ta(),innerWidth:this.va(),innerHeight:this.ua()})}Gc(e){e?this.A.vc():this.A.Ic();z(this,"visibilitychange",{hidden:e})}zd(e,f){"Backspace"===f.key&&y(f);const c=b.get(f.code)||f.code;F(this,e,{code:c,key:f.key,which:f.which,repeat:f.repeat,altKey:f.altKey,ctrlKey:f.ctrlKey,metaKey:f.metaKey,shiftKey:f.shiftKey,timeStamp:f.timeStamp},d)}Cf(e){z(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Ec(e,f,c){a(f)||F(this,e,{button:f.button,buttons:f.buttons,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:f.movementX||0,movementY:f.movementY||0,timeStamp:f.timeStamp},c)}Fc(e,f){if(!a(f)){var c=this.mb;"pointerdown"===e&&0!==c?e="pointermove":"pointerup"===e&&0!==f.buttons&&(e="pointermove");F(this,e,{pointerId:1,pointerType:"mouse",button:f.button,buttons:f.buttons,lastButtons:c,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,
movementX:f.movementX||0,movementY:f.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:f.timeStamp},d);this.mb=f.buttons;this.Ec(f.type,f,g)}}Wa(e,f){if(this.pb&&"pointermove"!==e){var c=this.pb;c.eb||(M(c),c.Pb=Date.now())}c=0;"mouse"===f.pointerType&&(c=this.mb);F(this,e,{pointerId:f.pointerId,pointerType:f.pointerType,button:f.button,buttons:f.buttons,lastButtons:c,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:(f.movementX||
0)+this.Wb,movementY:(f.movementY||0)+this.Xb,width:f.width||0,height:f.height||0,pressure:f.pressure||0,tangentialPressure:f.tangentialPressure||0,tiltX:f.tiltX||0,tiltY:f.tiltY||0,twist:f.twist||0,timeStamp:f.timeStamp},d);this.Xb=this.Wb=0;"mouse"===f.pointerType&&(c="mousemove","pointerdown"===e?c="mousedown":"pointerup"===e&&(c="mouseup"),this.Ec(c,f,g),this.mb=f.buttons)}Df(e){this.Ha&&(this.Wb+=this.Ha.movementX||0,this.Xb+=this.Ha.movementY||0);this.Ha=e;e=this.pb;if(-1===e.Pa){var f=Date.now(),
c=f-e.Pb,k=e.ug;c>=k&&e.Kd?(e.Pb=f,e.eb=!0,e.Lc(),e.eb=!1):e.Pa=self.setTimeout(e.be,Math.max(k-c,4))}}af(){this.Wa("pointermove",this.Ha);this.Ha=null}Eb(e,f){for(let c=0,k=f.changedTouches.length;c<k;++c){const l=f.changedTouches[c];F(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,movementX:f.movementX||0,movementY:f.movementY||0,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||
0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:f.timeStamp},d)}}zc(e){window!==window.top&&window.focus();this.xd(e.target)&&document.activeElement&&!this.xd(document.activeElement)&&document.activeElement.blur()}xd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Se(){this.Hd||(this.Hd=!0,window.addEventListener("deviceorientation",e=>this.sf(e)),window.addEventListener("deviceorientationabsolute",
e=>this.tf(e)))}Re(){this.Gd||(this.Gd=!0,window.addEventListener("devicemotion",e=>this.rf(e)))}sf(e){z(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}tf(e){z(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}rf(e){let f=null;var c=e.acceleration;c&&(f=
{x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=e.accelerationIncludingGravity;k&&(c={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});z(this,"devicemotion",{acceleration:f,accelerationIncludingGravity:c,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},d)}Lf(e){const f=this.A.K;f.style.width=e.styleWidth+"px";f.style.height=e.styleHeight+"px";f.style.marginLeft=e.marginLeft+"px";f.style.marginTop=e.marginTop+"px";this.Pd&&(f.style.display=
"",this.Pd=!1)}yf(e){const f=e.url;e=e.filename;const c=document.createElement("a"),k=document.body;c.textContent=e;c.href=f;c.download=e;k.appendChild(c);c.click();k.removeChild(c)}async Ff(e){var f=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);f=f?await createImageBitmap(e,f):await createImageBitmap(e);return{imageBitmap:f,transferables:[f]}}async wf(e){return await self.C3_GetSvgImageSize(e.blob)}async kf(e){await p(e.url)}Hc(){var e=
[...this.Ja];this.Ja.clear();if(!this.na)for(const f of e)(e=f.play())&&e.catch(()=>{this.Sb.has(f)||this.Ja.add(f)})}ta(e){if("function"!==typeof e.play)throw Error("missing play function");this.Sb.delete(e);let f;try{f=e.play()}catch(c){this.Ja.add(e);return}f&&f.catch(()=>{this.Sb.has(e)||this.Ja.add(e)})}Ba(e){this.Ja.delete(e);this.Sb.add(e)}Ab(e){this.na=!!e}xf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}qf(e){if(e.show){this.xa||(this.xa=document.createElement("div"),
this.xa.id="inspectOutline",document.body.appendChild(this.xa));var f=this.xa;f.style.display="";f.style.left=e.left-1+"px";f.style.top=e.top-1+"px";f.style.width=e.width+2+"px";f.style.height=e.height+2+"px";f.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Gf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ad(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}hf(e,f){return this.A.nd(this.Za,"js-invoke-function",{name:e,params:f},void 0,void 0)}lf(e){alert(e.message)}Nf(e){"entered-fullscreen"===
e?(h.Fd(!0),this.Va()):"exited-fullscreen"===e?(h.Fd(!1),this.Va()):console.warn("Unknown wrapper message: ",e)}})}"use strict";async function O(h){if(h.tg)throw Error("already initialised");h.tg=!0;var a=h.$b.yc("dispatchworker.js");h.Nc=await h.$b.fc(a,h.F,{name:"DispatchWorker"});a=new MessageChannel;h.Rc=a.port1;h.Nc.postMessage({type:"_init","in-port":a.port2},[a.port2]);h.Xc=await Q(h)}function P(h){return[h.Rc,h.Xc]}
async function Q(h){const a=h.Qd.length;var b=h.$b.yc("jobworker.js");b=await h.$b.fc(b,h.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;h.Nc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);h.Qd.push(b);return g.port1}
self.De=class{constructor(h){this.$b=h;this.F=h.F;this.F="preview"===h.v?this.F+"workers/":this.F+h.ac;this.wg=Math.min(navigator.hardwareConcurrency||2,16);this.Nc=null;this.Qd=[];this.Xc=this.Rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.qc({Lg:!0,Mg:"workermain.js",Qa:["scripts/c3runtime.js"],dc:[],ad:"",Ig:"scripts/",cd:[],ce:"html5"}));"use strict";
{const h=180/Math.PI;self.da=class extends self.hc{constructor(a){super(a,"audio");this.Lb=this.f=null;this.Nb=this.Qc=!1;this.qa=()=>this.pg();this.$=[];this.D=[];this.ga=null;this.Rd="";this.Sd=-1;this.ob=new Map;this.Uc=1;this.na=!1;this.$c=0;this.bc=1;this.Oc=0;this.Ud="HRTF";this.Ld="inverse";this.Vd=600;this.Td=1E4;this.Xd=1;this.Nd=this.Yc=!1;this.$d=this.A.Be();this.aa=new Map;this.Fa=new Set;this.Sc=!1;this.Vc="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Bf(b,d);this.Kb=null;
self.C3Audio_GetOutputStream=()=>this.vf();self.C3Audio_DOMInterface=this;J(this,[["create-audio-context",b=>this.Xe(b)],["play",b=>this.Pf(b)],["stop",b=>this.mg(b)],["stop-all",()=>this.ng()],["set-paused",b=>this.fg(b)],["set-volume",b=>this.kg(b)],["fade-volume",b=>this.bf(b)],["set-master-volume",b=>this.dg(b)],["set-muted",b=>this.eg(b)],["set-silent",b=>this.hg(b)],["set-looping",b=>this.cg(b)],["set-playback-rate",b=>this.gg(b)],["seek",b=>this.Wf(b)],["preload",b=>this.Qf(b)],["unload",b=>
this.qg(b)],["unload-all",()=>this.rg()],["set-suspended",b=>this.ig(b)],["add-effect",b=>this.sd(b)],["set-effect-param",b=>this.$f(b)],["remove-effects",b=>this.Sf(b)],["tick",b=>this.Kf(b)],["load-state",b=>this.zf(b)]])}async Xe(a){a.isiOSCordova&&(this.Yc=!0);this.$c=a.timeScaleMode;this.Ud=["equalpower","HRTF","soundfield"][a.panningModel];this.Ld=["linear","inverse","exponential"][a.distanceModel];this.Vd=a.refDistance;this.Td=a.maxDistance;this.Xd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.$d||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.td();this.f.onstatechange=()=>{"running"!==this.f.state&&this.td()};this.Lb=this.f.createGain();this.Lb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.ic();try{await Promise.all(a.preloadList.map(d=>this.Cb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}td(){this.Nb||(this.Qc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Nb=!0)}Ze(){this.Nb&&(this.Qc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Nb=!1)}pg(){if(!this.Qc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ze()}}W(){return this.f}ic(){return this.f.currentTime}ra(){return this.Lb}kd(a){return(a=this.aa.get(a.toLowerCase()))?a[0].P():this.ra()}de(a,b){a=a.toLowerCase();let d=this.aa.get(a);
d||(d=[],this.aa.set(a,d));b.bg(d.length);b.jg(a);d.push(b);this.Dd(a)}Dd(a){let b=this.ra();const d=this.aa.get(a);if(d&&d.length){b=d[0].P();for(let g=0,m=d.length;g<m;++g){const p=d[g];g+1===m?p.S(this.ra()):p.S(d[g+1].P())}}for(const g of this.la(a))g.Ie(b);this.ya&&this.Vc===a&&(this.ya.disconnect(),this.ya.connect(b))}wb(){return this.Uc}xb(){return this.na}ag(){this.Nd=!0}ve(a,b){return b?this.A.sg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}ta(a){this.A.ta(a)}Ba(a){this.A.Ba(a)}od(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const m=this.D[d];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Je(){let a=0;for(let b=0,d=this.$.length;b<d;++b){const g=this.$[b];this.$[a]=g;g.sa()?g.c():++a}this.$.length=a}*la(a){if(a)for(const b of this.D)self.da.we(b.Y,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Cb(a,b,d,g,m){for(const p of this.$)if(p.Sa()===b)return await R(p),p;
if(m)return null;g&&(this.Yc||this.Nd)&&this.Je();m="audio/webm; codecs=opus"===d&&!this.$d;g&&m&&this.ag();a=!g||this.Yc||m?new self.re(this,a,b,d,g,m):new self.pe(this,a,b,d,g);this.$.push(a);await R(a);return a}async xc(a,b,d,g,m){for(const p of this.D)if(p.Sa()===b&&(p.ec()||m))return p.Le(g),p;a=await this.Cb(a,b,d,m);g="html5"===a.Jc?new self.qe(a.i,a,g):new self.se(a.i,a,g);this.D.push(g);return g}Pe(a){let b=this.ob.get(a);if(!b){let d=null;b={bd:0,Hg:new Promise(g=>d=g),resolve:d};this.ob.set(a,
b)}b.bd++}Tf(a){const b=this.ob.get(a);if(!b)throw Error("expected pending tag");b.bd--;0===b.bd&&(b.resolve(),this.ob.delete(a))}uc(a){a||(a=this.Rd);return(a=this.ob.get(a))?a.Hg:Promise.resolve()}Db(){if(0<this.Fa.size)L(this);else for(const a of this.D)if(a.ld()){L(this);break}}Ca(){for(var a of this.Fa)a.Ca();a=this.ic();for(var b of this.D)b.Ca(a);b=this.D.filter(d=>d.ld()).map(d=>d.Ra());z(this,"state",{tickCount:this.Sd,audioInstances:b,analysers:[...this.Fa].map(d=>d.ye())});0===b.length&&
0===this.Fa.size&&this.Ob&&(this.A.Uf(this.ae),this.Ob=!1)}pc(a,b,d){z(this,"trigger",{type:a,tag:b,aiid:d})}async Pf(a){const b=a.originalUrl,d=a.url,g=a.type,m=a.isMusic,p=a.tag,w=a.isLooping,A=a.vol,B=a.pos,u=a.panning;let v=a.off;0<v&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),v=v-a.performanceTime/1E3+a.contextTime):v=v-performance.now()/1E3+this.f.currentTime);this.Rd=p;this.Pe(p);try{this.ga=await this.xc(b,d,g,p,m),u?(this.ga.zb(!0),this.ga.Ke(u.x,u.y,u.angle,
u.innerAngle,u.outerAngle,u.outerGain),u.hasOwnProperty("uid")&&this.ga.Me(u.uid)):this.ga.zb(!1),this.ga.Play(w,A,B,v)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Tf(p)}L(this)}mg(a){a=a.tag;for(const b of this.la(a))b.ma()}ng(){for(const a of this.D)a.ma()}fg(a){const b=a.tag;a=a.paused;for(const d of this.la(b))a?d.Ua():d.yb();this.Db()}kg(a){const b=a.tag;a=a.vol;for(const d of this.la(b))d.Bb(a)}async bf(a){const b=a.tag,d=a.vol,g=a.duration;
a=a.stopOnEnd;await this.uc(b);for(const m of this.la(b))m.xe(d,g,a);this.Db()}dg(a){this.Uc=a.vol;for(const b of this.D)b.Ib()}eg(a){const b=a.tag;a=a.isMuted;for(const d of this.la(b))d.pd(a)}hg(a){this.na=a.isSilent;this.A.Ab(this.na);for(const b of this.D)b.Hb()}cg(a){const b=a.tag;a=a.isLooping;for(const d of this.la(b))d.sc(a)}async gg(a){const b=a.tag;a=a.rate;await this.uc(b);for(const d of this.la(b))d.rd(a)}async Wf(a){const b=a.tag;a=a.pos;await this.uc(b);for(const d of this.la(b))d.rc(a)}async Qf(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.xc(b,d,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async qg(a){if(a=await this.Cb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.$.indexOf(a),-1!==a&&this.$.splice(a,1)}rg(){for(const a of this.$)a.c();this.$.length=0}ig(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.tc(a);a&&this.f.suspend&&this.f.suspend()}Kf(a){this.bc=a.timeScale;this.Oc=a.gameTime;this.Sd=a.tickCount;if(0!==this.$c)for(var b of this.D)b.Ea();
(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.fa===a&&g.qd(d.x,d.y,d.angle)}}async sd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.je(this,...g);else if("delay"===b)g=new self.he(this,...g);else if("convolution"===b){b=null;try{b=await this.Cb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",m);return}g=new self.ge(this,b.Z,
...g);g.Yf(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ke(this,...g);else if("phaser"===b)g=new self.me(this,...g);else if("gain"===b)g=new self.le(this,...g);else if("tremolo"===b)g=new self.oe(this,...g);else if("ringmod"===b)g=new self.ne(this,...g);else if("distortion"===b)g=new self.ie(this,...g);else if("compressor"===b)g=new self.fe(this,...g);else if("analyser"===b)g=new self.ee(this,...g);else throw Error("invalid effect type");this.de(d,g);this.Cd()}$f(a){const b=
a.index,d=a.param,g=a.value,m=a.ramp,p=a.time;a=this.aa.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,m,p),this.Cd())}Sf(a){a=a.tag.toLowerCase();const b=this.aa.get(a);if(b&&b.length){for(const d of b)d.c();this.aa.delete(a);this.Dd(a)}}Oe(a){this.Fa.add(a);this.Db()}Rf(a){this.Fa.delete(a)}Cd(){this.Sc||(this.Sc=!0,Promise.resolve().then(()=>this.$e()))}$e(){const a={};for(const [b,d]of this.aa)a[b]=d.map(g=>g.Ra());z(this,"fxstate",{fxstate:a});this.Sc=!1}async zf(a){const b=a.saveLoadMode;if(3!==
b)for(var d of this.D)d.sa()&&1===b||(d.sa()||2!==b)&&d.ma();for(const g of this.aa.values())for(const m of g)m.c();this.aa.clear();this.bc=a.timeScale;this.Oc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.na=a.isSilent;this.A.Ab(this.na);this.Uc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(m=>this.sd(m))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.jf(g,b)));this.Db()}async jf(a,b){if(3!==b){var d=a.bufferOriginalUrl,
g=a.bufferUrl,m=a.bufferType,p=a.isMusic,w=a.tag,A=a.isLooping,B=a.volume,u=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.xc(d,g,m,w,p)}catch(v){console.error("[Construct 3] Audio: error loading audio state: ",v);return}b.Ge(a.pan);b.Play(A,B,u,0);a.isPlaying||b.Ua();b.Bc(a)}}}Bf(a,b){this.ya&&this.ya.disconnect();this.Vc=b.toLowerCase();this.ya=this.f.createMediaStreamSource(a);this.ya.connect(this.kd(this.Vc))}vf(){this.Kb||(this.Kb=this.f.createMediaStreamDestination(),this.Lb.connect(this.Kb));
return this.Kb.stream}static we(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ne(a){return a*h}static ue(a){return Math.pow(10,a/20)}static jd(a){return Math.max(Math.min(self.da.ue(a),1),0)}static Fe(a){return Math.log(a)/Math.log(10)*20}static Ee(a){return self.da.Fe(Math.max(Math.min(a,1),0))}static Cg(a,b){return 1-Math.exp(-b*a)}};self.qc.dd(self.da)}"use strict";function R(h){h.Qb||(h.Qb=h.Ac());return h.Qb}
self.fd=class{constructor(h,a,b,d,g){this.i=h;this.yg=a;this.za=b;this.R=d;this.vg=g;this.Jc="";this.Qb=null}c(){this.Qb=this.i=null}Ac(){}W(){return this.i.W()}kc(){return this.yg}Sa(){return this.za}jc(){return this.R}sa(){return this.vg}ea(){}};"use strict";
self.pe=class extends self.fd{constructor(h,a,b,d,g){super(h,a,b,d,g);this.Jc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.ib=this.jb=null;this.J.addEventListener("canplaythrough",()=>!0);this.nb=this.W().createGain();this.lb=null;this.J.addEventListener("canplay",()=>{this.jb&&(this.jb(),this.ib=this.jb=null);!this.lb&&this.J&&(this.lb=this.W().createMediaElementSource(this.J),this.lb.connect(this.nb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.za}' error: `,m);this.ib&&(this.ib(m),this.ib=this.jb=null)})}c(){this.i.od(this);this.nb.disconnect();this.nb=null;this.lb.disconnect();this.lb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Ac(){return new Promise((h,a)=>{this.jb=h;this.ib=a;this.J.src=this.za})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function S(h){if(h.wa)return h.wa;var a=h.i.A;if("cordova"===a.v&&a.md(h.za)&&a.fb)h.wa=await a.ub(h.za);else{a=await fetch(h.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.wa=await a.arrayBuffer()}}async function T(h){if(h.Z)return h.Z;h.Z=await h.i.ve(h.wa,h.xg);h.wa=null}
self.re=class extends self.fd{constructor(h,a,b,d,g,m){super(h,a,b,d,g);this.Jc="webaudio";this.Z=this.wa=null;this.xg=!!m}c(){this.i.od(this);this.Z=this.wa=null;super.c()}async Ac(){try{await S(this),await T(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.za}': `,h)}}ea(){return this.Z?this.Z.duration:0}};"use strict";
{let h=0;self.gd=class{constructor(a,b,d){this.i=a;this.L=b;this.Y=d;this.Jb=h++;this.M=this.W().createGain();this.M.connect(this.ra());this.B=null;this.gb=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.H=!0;this.V=this.ka=this.G=!1;this.rb=1;this.Ga=!1;this.pa=1;a=this.i.$c;this.Tc=1===a&&!this.sa()||2===a;this.bb=this.fa=-1;this.Zd=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ra(){return this.i.kd(this.Y)}wb(){return this.i.wb()}vb(){return this.Tc?
this.i.Oc:performance.now()/1E3}kc(){return this.L.kc()}Sa(){return this.L.Sa()}jc(){return this.L.jc()}sa(){return this.L.sa()}Le(a){this.Y=a}T(){}ec(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}ld(){return!this.H&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}ma(){}Ua(){}yb(){}Bb(a){this.rb=a;this.M.gain.cancelScheduledValues(0);this.bb=-1;this.M.gain.value=this.lc()}xe(a,b,d){if(!this.Ga){a*=this.wb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.ic();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.rb=a;this.bb=b;this.Zd=d}}Ib(){this.Bb(this.rb)}Ca(a){-1!==this.bb&&a>=this.bb&&(this.bb=-1,this.Zd&&this.ma(),this.i.pc("fade-ended",this.Y,this.Jb))}lc(){const a=this.rb*this.wb();return isFinite(a)?a:0}pd(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Hb())}xb(){return this.i.xb()}Hb(){}sc(){}rd(a){this.pa!==a&&(this.pa=a,this.Ea())}Ea(){}rc(){}tc(){}zb(a){a=!!a;this.gb!==a&&((this.gb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Ud,this.B.distanceModel=
this.i.Ld,this.B.refDistance=this.i.Vd,this.B.maxDistance=this.i.Td,this.B.rolloffFactor=this.i.Xd),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ra())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ra())))}Ke(a,b,d,g,m,p){this.gb&&(this.qd(a,b,d),a=self.da.Ne,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}qd(a,b,d){this.gb&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(d),this.ia[1]=Math.sin(d),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Me(a){this.fa=a}mc(){}Ie(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Jb,tag:this.Y,duration:this.ea(),volume:this.rb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.pa,uid:this.fa,bufferOriginalUrl:this.kc(),bufferUrl:"",bufferType:this.jc(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.mc(),pan:this.ze()}}Bc(a){this.rd(a.playbackRate);this.pd(a.isMuted)}ze(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Ge(a){if(a){this.zb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.zb(!1)}}}"use strict";
self.qe=class extends self.gd{constructor(h,a,b){super(h,a,b);this.L.nb.connect(this.M);this.L.onended=()=>this.Cc()}c(){this.ma();this.L.nb.disconnect();super.c()}O(){return this.L.O()}Cc(){this.H=!0;this.fa=-1;this.i.pc("ended",this.Y,this.Jb)}T(){return this.O().ended}ec(){return this.H?!0:this.T()}Aa(){let h=this.O().currentTime;this.V||(h=Math.min(h,this.ea()));return h}Play(h,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==h&&(d.loop=h);this.Bb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,g)}this.i.ta(d);this.G=this.H=!1;this.V=h;this.pa=1}ma(){const h=this.O();h.paused||h.pause();this.i.Ba(h);this.H=!0;this.G=!1;this.fa=-1}Ua(){if(!(this.G||this.H||this.T())){var h=this.O();h.paused||h.pause();this.i.Ba(h);this.G=!0}}yb(){!this.G||this.H||this.T()||(this.i.ta(this.O()),this.G=!1)}Hb(){this.O().muted=this.Ga||this.xb()}sc(h){h=!!h;this.V!==h&&
(this.V=h,this.O().loop=h)}Ea(){let h=this.pa;this.Tc&&(h*=this.i.bc);try{this.O().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}rc(h){if(!this.H&&!this.T())try{this.O().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}mc(){return this.Aa()}tc(h){h?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.ta(this.O()),this.ka=!1)}};"use strict";
function U(h){h.j&&h.j.disconnect();h.j=null;h.Ya=null}
self.se=class extends self.gd{constructor(h,a,b){super(h,a,b);this.j=null;this.Tb=d=>this.Cc(d);this.Pc=!0;this.Ya=null;this.N=this.Ub=this.Vb=0;this.Wc=1}c(){this.ma();U(this);this.Tb=null;super.c()}Cc(h){this.G||this.ka||h.target!==this.Ya||(this.H=this.Pc=!0,this.fa=-1,U(this),this.i.pc("ended",this.Y,this.Jb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Pc}ec(){return!this.j||this.H?!0:this.T()}Aa(){let h;h=this.G?this.N:this.Ub+(this.vb()-this.Vb)*this.pa;this.V||(h=Math.min(h,this.ea()));
return h}Play(h,a,b,d){this.Wc=1;this.Bb(a);U(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.Z;this.j.connect(this.M);this.Ya=this.j;this.j.onended=this.Tb;this.j.loop=h;this.j.start(d,b);this.G=this.H=this.Pc=!1;this.V=h;this.pa=1;this.Vb=this.vb();this.Ub=b}ma(){if(this.j)try{this.j.stop(0)}catch(h){}this.H=!0;this.G=!1;this.fa=-1}Ua(){this.G||this.H||this.T()||(this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}yb(){!this.G||this.H||this.T()||(U(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Tb,this.j.loop=this.V,this.Ib(),this.Ea(),this.j.start(0,this.N),this.Vb=this.vb(),this.Ub=this.N,this.G=!1)}lc(){return super.lc()*this.Wc}Hb(){this.Wc=this.Ga||this.xb()?0:1;this.Ib()}sc(h){h=!!h;this.V!==h&&(this.V=h,this.j&&(this.j.loop=h))}Ea(){let h=this.pa;this.Tc&&(h*=this.i.bc);this.j&&(this.j.playbackRate.value=h)}rc(h){this.H||this.T()||(this.G?this.N=h:(this.Ua(),this.N=h,this.yb()))}mc(){return this.N}tc(h){h?
this.IsPlaying()?(this.ka=!0,this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(U(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Tb,this.j.loop=this.V,this.Ib(),this.Ea(),this.j.start(0,this.N),this.Vb=this.vb(),this.Ub=this.N,this.ka=!1)}Bc(h){super.Bc(h);this.N=h.resumePosition}};"use strict";
{class h{constructor(a){this.i=a;this.f=a.W();this.Od=-1;this.R=this.Y="";this.g=null}c(){this.f=null}bg(a){this.Od=a}jg(a){this.Y=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ra(){return{type:this.R,tag:this.Y,params:this.g}}}
self.je=class extends h{constructor(a,b,d,g,m,p,w){super(a);this.R="filter";this.g=[b,d,g,m,p,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,g)}}};self.he=class extends h{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.kb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.ab=this.o();this.ab.gain.value=d;this.l.connect(this.kb);this.l.connect(this.a);this.kb.connect(this.b);this.kb.connect(this.U);this.U.connect(this.ab);this.ab.connect(this.kb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.kb.disconnect();this.U.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const m=self.da.jd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=m(b);this.m(this.ab.gain,m(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.ge=class extends h{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Jd=this.Id="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.$a=this.f.createConvolver();this.$a.normalize=d;this.$a.buffer=b;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b)}c(){this.l.disconnect();this.$a.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Yf(a,b){this.Id=a;this.Jd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Id;a.bufferUrl="";a.bufferType=this.Jd;return a}};self.ke=class extends h{constructor(a,b,d,g,m,p){super(a);this.R="flanger";this.g=[b,d,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.cb=this.o();this.cb.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.cb);this.cb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.cb.gain,b/100,d,g)}}};self.me=class extends h{constructor(a,b,d,g,m,p,w){super(a);this.R="phaser";this.g=[b,d,g,m,p,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.le=class extends h{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const m=self.da.jd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,g)}}};self.oe=class extends h{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ne=class extends h{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.qb=this.o();this.qb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.qb.gain);this.s.start(0);this.l.connect(this.qb);this.l.connect(this.a);this.qb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.qb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ie=class extends h{constructor(a,b,d,g,m,p){super(a);this.R="distortion";this.g=[b,d,g,m,p];this.l=this.o();this.Zb=this.o();this.Yb=this.o();this.Zf(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.cc=this.f.createWaveShaper();this.Mc=new Float32Array(65536);this.df(b,d);this.cc.curve=this.Mc;this.l.connect(this.Zb);this.l.connect(this.a);this.Zb.connect(this.cc);this.cc.connect(this.Yb);
this.Yb.connect(this.b)}c(){this.l.disconnect();this.Zb.disconnect();this.cc.disconnect();this.Yb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Zf(a,b){.01>a&&(a=.01);this.Zb.gain.value=a;this.Yb.gain.value=Math.pow(1/a,.6)*b}df(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.lg(g,a,b);this.Mc[32768+d]=g;this.Mc[32768-d-1]=-g}}lg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.Cg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.fe=class extends h{constructor(a,b,d,g,m,p){super(a);this.R="compressor";this.g=[b,d,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ee=class extends h{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Md=new Float32Array(this.h.frequencyBinCount);this.Yd=new Uint8Array(b);this.Wd=this.Ka=0;this.i.Oe(this)}c(){this.i.Rf(this);this.h.disconnect();super.c()}Ca(){this.h.getFloatFrequencyData(this.Md);this.h.getByteTimeDomainData(this.Yd);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let g=(this.Yd[d]-128)/128;0>g&&(g=-g);
this.Ka<g&&(this.Ka=g);b+=g*g}d=self.da.Ee;this.Ka=d(this.Ka);this.Wd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}ye(){return{tag:this.Y,index:this.Od,peak:this.Ka,rms:this.Wd,binCount:this.h.frequencyBinCount,freqBins:this.Md}}}};
